### ISSUE TITLE
A srcset attribute URL parser required for responsive images

### ISSUE THREAD

**Issue by rokibulislaam** [rokibulislaam/Wordpress.com_lowdb#5]
WordPress posts maintain `srcset` attribute throughout all the posts to serve responsive images to the client.

A URL parser for those `srcset` attributes would allow us to do the same as mentioned above.

The working should be like:
The parser would extract the `srcset` attribute of the `img` tag and traverse over all the URLs and parse the URLs and return clean URLs for `srcset`.

Please refer to the PR #4 and commit 761cc34264d6967fb464ce3602c27da25c036a72 for more information.

**Comment by tasnimzotder** [comment]
hey @rokibulislaam Can I tackle this issue?

**Comment by rokibulislaam** [comment]
> hey @rokibulislaam Can I tackle this issue?

sure, I'm assigning you then!
